spring.application.name=crud-empleados-spring-mvc

# ===================================================================
# CONFIGURACION DEL SERVIDOR (Tomcat 11 / Jakarta EE 11)
# ===================================================================
spring.profiles.active=dev
server.address=127.0.0.1
#spring.profiles.active=prod
#server.address=192.168.1.42
server.port=8080

# Estrategia de cabeceras proxy (Reemplaza por completo al obsoleto use-forward-headers)
server.forward-headers-strategy=native

# ===================================================================
# RENDIMIENTO MAXIMO (Java 21 Virtual Threads & Compresión)
# ===================================================================
spring.threads.virtual.enabled=true

# Habilitar la compresión de respuesta HTTP
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,application/xml,text/plain,application/json
server.compression.min-response-size=1024

# Habilita la espera de finalización de tareas al apagar el servidor
spring.task.scheduling.shutdown.await-termination=true
spring.task.scheduling.shutdown.await-termination-period=15s
