#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
# ===================================================================
# CONFIGURACION DEL SERVIDOR (Tomcat 11 / Jakarta EE 11)
# ===================================================================
server.port=8080
server.compression.enabled=true
spring.web.error.include-stacktrace=always

# Estrategia de cabeceras proxy nativa
server.forward-headers-strategy=native

# ===================================================================
# RENDIMIENTO MAXIMO (Java 25 Virtual Threads) soporta miles de peticiones simultáneas consumiendo una cantidad mínima de RAM.
# ===================================================================
spring.threads.virtual.enabled=true

# ===================================================================
# RECURSOS ESTATICOS
# ===================================================================
spring.web.resources.static-locations=classpath:/static/,file:uploads/

# ===================================================================
# POOL DE DATOS STANDARD: BASE DE DATOS PRINCIPAL (MySQL 8.4 LTS)
# ===================================================================
empleados.datasource.url=jdbc:mysql://192.168.122.43:3306/crud_empleados_spring_mvc?createDatabaseIfNotExist=true&serverTimezone=UTC
empleados.datasource.username=${DB_MYSQL_USERNAME}
empleados.datasource.password=${DB_MYSQL_PASSWORD}
empleados.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
empleados.datasource.hikari.maximum-pool-size=30

# ===================================================================
# POOL DE DATOS STANDARD: BASE DE DATOS LANGUAGE (PostgreSQL)
# ===================================================================
lang.datasource.url=jdbc:postgresql://192.168.122.43:5432/lang
lang.datasource.username=${DB_LANG_USERNAME}
lang.datasource.password=${DB_LANG_PASSWORD}
lang.datasource.driver-class-name=org.postgresql.Driver
lang.datasource.hikari.maximum-pool-size=30

# ===================================================================
# CONFIGURACION GLOBAL DE HIBERNATE / JPA
# ===================================================================
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

##### Files properties PROPERTIES
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Extensiones de imagen permitidas en la aplicación
app.upload.allowed-extensions=.jpg,.jpeg,.png,.webp
